### ISSUE TITLE
Project #1 Feedback

### ISSUE THREAD

**Issue by jadencarver** [AndrewGarver/project_1#1]
Your HTML is quite well formed. You should indent the tags though. Employers will be very critical of how your code looks and it really helps readability. It also makes bugs less likely to be introduced due to "the broken windows" effect: 

> Consider a building with a few broken windows. If the windows are not repaired, the tendency is for 
> vandals to break a few more windows. Eventually, they may even break into the building, and if it's 
> unoccupied, perhaps become squatters or light fires inside.

Great job with your CSS! You could have used a Multi-Class selector to clean it up a bit, simplify your JS and make it more clear like:

```css
.green {
  background-color: green;
}
.green.flash {
  background-color: #90EE90;
}
.red {
  background-color: red;
}
.red.flash {
  background-color: pink;
}
```

With that CSS, your JavaScript would just need to add/remove the 'flash' class instead of having to pick the right `.flashgreen`,`.flashred`, etc.

Awesome use of `on` and `off`! to enable/disable the click handlers. It also looks like GitHub may have scrambled your indentation. I believe there is a setting in Sublime that will fix this to always use tabs. Ultimately the problem is that GitHub uses 8-character tabs, and we use 2-space tabs.

The Game-logic is a bit off, creating an entirely new sequence each turn instead of replaying the previous, adding an additional color - but that's fine.

Great Job!
